# Generated by Django 4.1.7 on 2023-08-13 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('announcement_date', models.DateField(auto_now_add=True)),
                ('last_registration_date', models.DateTimeField()),
                ('event_date', models.DateTimeField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='event')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='event')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='event')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='event')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='event')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('project_link', models.URLField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='project')),
                ('project_lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
