# Generated by Django 4.1.7 on 2023-08-20 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_blog_events_projects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='program',
            new_name='branch',
        ),
    ]
